// actions.js — All action type constants. No magic strings elsewhere.

export const ACTIONS = {
  SET_API_KEY:       'SET_API_KEY',
  SET_VIEW:          'SET_VIEW',
  SET_MILESTONES:    'SET_MILESTONES',
  SET_PROJECT:       'SET_PROJECT',
  SET_ESCROW:        'SET_ESCROW',
  APPEND_LEDGER:     'APPEND_LEDGER',
  SET_AQA_RESULT:    'SET_AQA_RESULT',
  SET_FREELANCERS:   'SET_FREELANCERS',
  SET_LOADING:       'SET_LOADING',
  SET_ERROR:         'SET_ERROR',
  SET_PFI_SCORE:     'SET_PFI_SCORE',
  SET_ASSIGN_SCORES: 'SET_ASSIGN_SCORES',
  PUSH_HITL:         'PUSH_HITL',
  RESOLVE_HITL:      'RESOLVE_HITL',
  UPDATE_PFI_CONFIG: 'UPDATE_PFI_CONFIG',
  SET_DAG:           'SET_DAG',
  SET_DECOMPOSITION: 'SET_DECOMPOSITION',
  RESET_STATE:       'RESET_STATE',
};
